### ISSUE TITLE
Create risk attributes in Project model

### ISSUE THREAD

**Issue by michellevlad** [adriancast/jerry#1]
Create the following read only attributes:
 - project in risk by delayed tasks: > 0.25 delayed tasks.
 - project in risk by exceded budget: estimated budget < costs

**Comment by adriancast** [comment]
Buenas @michellevlad ,

he aplicado la logica talcual. Aqui tienes un ejemplo:

![image](https://user-images.githubusercontent.com/17761956/120553919-5ed19a80-c3f9-11eb-8ca3-49c68b18a6d4.png)


un saludo!
