### ISSUE TITLE
Add project creation form the project configuration missing data

### ISSUE THREAD

**Issue by michellevlad** [adriancast/jerry#2]
In the project configuration form you can specify hours by resource. This must be also added in the Project model

**Comment by adriancast** [comment]
Buenas @michellevlad ,

he añadido los campos de los recursos y una estimacion dinamica de costes segun recursos. Esto lo podré reutilizar en la parte de los informes

![image](https://user-images.githubusercontent.com/17761956/120553160-78261700-c3f8-11eb-8954-63e692fa1931.png)
